default_styles = {
    "background_color": "#E0E0E0",
    "dark_color": "#505A5B",
    "light_color": "#FCFCFC",
    "primary_color": "#3F8EFC",
    "secondary_color": "#251F47",
    "heading_font": "Oswald",
    "body_font": "Barlow",
    "wrap_full_name": True,
    "wrap_current_job_title": False,
}


default_icons = {
    "android": "devicon-android-plain",
    "aws": "devicon-amazonwebservices-original",
    "bash": "devicon-bash-plain",
    "c": "devicon-c-plain",
    "cmake": "devicon-cmake-plain",
    "css": "fa-brands fa-css3-alt",
    "docker": "fa-brands fa-docker",
    "elixir": "devicon-elixir-plain",
    "email": "fa-regular fa-envelope",
    "facebook": "devicon-facebook-original",
    "gcp": "devicon-googlecloud-plain",
    "git": "fa-brands fa-git-alt",
    "github": "devicon-github-original",
    "go": "devicon-go-plain",
    "html": "fa-brands fa-html5",
    "java": "devicon-java-plain",
    "javascript": "devicon-javascript-plain",
    "kubernetes": "devicon-kubernetes-plain",
    "linkedin": "devicon-linkedin-plain",
    "linux": "fa-brands fa-linux",
    "packer": "devicon-packer-original",
    "phone": "bi bi-telephone",
    "postgresql": "devicon-postgresql-plain",
    "python": "fa-brands fa-python",
    "rust": "devicon-rust-plain",
    "selenium": "devicon-selenium-original",
    "twitter": "devicon-twitter-original",
    "website": "bi bi-globe",
    "windows": "bi bi-windows",
    "youtube": "fa-brands fa-youtube",
}
